# prefix
unbind C-s
set -g prefix C-s

# Terminal
set -g default-terminal "tmux-256color"

set -as terminal-features ",tmux-256color:RGB"
set -as terminal-features ",foot:RGB"
set -as terminal-features ",xterm-256color:RGB"

set -g xterm-keys on

# index
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# behavior
set -s escape-time 0
set -g repeat-time 0
set -g assume-paste-time 0
set -g mouse on
set -g focus-events on
set -g detach-on-destroy off
set -g automatic-rename on
set -g set-titles on
set -g history-limit 50000
setw -g aggressive-resize on

# splits
unbind '"'
bind o split-window -v -c "#{pane_current_path}"
unbind %
bind e split-window -h -c "#{pane_current_path}"

# windows
bind C new-window -c "#{pane_current_path}"
bind-key N command-prompt -p "window name [start in cwd]:" -I "typeshit" "new-window -n '%%' -c '#{pane_current_path}'"

# sessions
bind-key S command-prompt -p "session name [start in cwd]:" -I "#{s|.*/||:pane_current_path}" "new-session -s '%%' -c '#{pane_current_path}'"

# reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# toggle statusline
bind b set-option status

# copy mode
bind-key a copy-mode
setw -g mode-keys vi
bind -T copy-mode-vi v   send-keys -X begin-selection
bind -T copy-mode-vi V   send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# window navigation
bind -n S-Left  previous-window
bind -n S-Right next-window

# pane resize
bind -n C-S-Left  resize-pane -L 5
bind -n C-S-Right resize-pane -R 5
bind -n C-S-Up    resize-pane -U 5
bind -n C-S-Down  resize-pane -D 5

# status bar
set -g status-interval 30
set -g status-left-length 200
set -g status-right-length 40
set -g status-left ' #[fg=green] [#S] #[fg=green]• '
set -g status-right '#[fg=blue]󰍹  #(uptime --pretty)'

# colors
set-option -g display-panes-active-colour "#0B6DB3"
set-option -g display-panes-colour "#7dcfff"
set-option -g message-style "bg=#1a1b26,fg=#7dcfff"
set-option -g pane-active-border-style "fg=#0B6DB3"
set-option -g pane-border-style "fg=#32344a"
set-option -g status-style bg=default,fg=colour136
set-window-option -g clock-mode-colour green
set-window-option -g mode-style "fg=#1a1b26,bg=#7dcfff"
set-window-option -g window-status-current-style fg=#0B6DB3,bg=default,bright
set-window-option -g window-status-style fg=colour244,bg=default,dim

# window format
set -g window-status-current-format ' #W'
set -g window-status-format ' #W '

set -g extended-keys on
