#!/usr/bin/env bash

search_dirs=(
  /vagrant/projects
)
if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(
    for dir in "${search_dirs[@]}"; do
      find "$dir" -maxdepth 1 -type d,l -not -path '*/\.*' 2>/dev/null
    done | fzf
  )
fi
if [[ -z $selected ]]; then
  exit 0
fi
selected_name="$(basename "$selected" | tr . _)-opencode"
tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi
if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
fi
if [[ -z $TMUX ]]; then
  tmux attach -t "$selected_name"
else
  tmux switch-client -t "$selected_name"
fi
